language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t jonnyray/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jonnyray/docker-react npm run test -- --coverage